"""Add CheckConstraint min_length to Recipe.instructions

Revision ID: 30063f822b7d
Revises: da24d630e7a1
Create Date: 2024-04-18 14:15:27.397117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30063f822b7d'
down_revision = 'da24d630e7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
